spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5433/t1_demo"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      max.poll.records: 10
      session-timeout: 10000
      heartbeat.interval: 3000
    producer:
      enable: true
    topic:
      accounts: t1_demo_accounts
      transactions: t1_demo_transactions
      metrics: t1_demo_metrics
      acceptance:  t1_demo_transaction_accept
      result: t1_demo_transaction_result
    listener:
      poll-timeout: 1000
    custom-settings:
      maximum: 2
      minutes: 3