server:
  port: 8090
spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5433/t1_demo"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      max.poll.records: 10
      session-timeout: 10000
      heartbeat.interval: 3000
    producer:
      enable: true
    topic:
      acceptance: t1_demo_transaction_accept
      result: t1_demo_transaction_result
    listener:
      poll-timeout: 1000
