version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: t1_java_demo
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: t1_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
