# запросы, которые вызывают исключения при CRUD-операциях


# слишком длинное имя
POST http://localhost:8080/clients/new
Content-Type: application/json

{
  "first_name": "Ranis",
  "last_name": "Zagidulin",
  "middle_name": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
}

###
# несуществующий AccountType
POST http://localhost:8080/accounts/new
Content-Type: application/json

{"client_id" : 200,
  "account_type" : "xxxx",
  "balance": 8888.00}

###
# ссылка на клиента с несуществующим id
POST http://localhost:8080/accounts/new
Content-Type: application/json

{"client_id" : 366,
  "account_type" : "DEBIT",
  "balance": 8888.00}

###
# запрос к несуществующей транзакции
GET http://localhost:8080/transactions/800
###
# просмотреть базу логов ошибок
GET http://localhost:8080/err
