create table account (
  id bigint primary key generated by default as identity ,
    client_id bigint references client(id) on delete cascade,
    account_type varchar(20) not null,
    balance numeric(10, 2) not null default 0.00
);

create table transaction (
    id bigint primary key generated by default as identity ,
    account_id int references account(id) on delete cascade,
    amount numeric(10, 2) not null,
    transaction_time timestamp not null default current_timestamp
);

create table data_source_error_log (
    id bigint primary key generated by default as identity ,
    stacktrace text not null,
    message varchar not null,
    method_signature varchar(255) not null,
    error_time timestamp not null default current_timestamp
);