insert into account (client_id, account_type, balance) values (181, 'CREDIT', 13297.00);
insert into account (client_id, account_type, balance) values (120, 'DEBIT', 15735.00);
insert into account (client_id, account_type, balance) values (103, 'CREDIT', 9807.00);
insert into account (client_id, account_type, balance) values (20, 'DEBIT', 15598.00);
insert into account (client_id, account_type, balance) values (39, 'DEBIT', 6302.00);
insert into account (client_id, account_type, balance) values (189, 'DEBIT', 115.00);
insert into account (client_id, account_type, balance) values (45, 'CREDIT', 168.00);
insert into account (client_id, account_type, balance) values (112, 'DEBIT', 18574.00);
insert into account (client_id, account_type, balance) values (56, 'DEBIT', 5983.00);
insert into account (client_id, account_type, balance) values (11, 'DEBIT', 18996.00);
insert into account (client_id, account_type, balance) values (76, 'CREDIT', 16348.00);
insert into account (client_id, account_type, balance) values (31, 'DEBIT', 17026.00);
insert into account (client_id, account_type, balance) values (12, 'CREDIT', 19367.00);
insert into account (client_id, account_type, balance) values (12, 'DEBIT', 4785.00);
insert into account (client_id, account_type, balance) values (18, 'CREDIT', 9853.00);
insert into account (client_id, account_type, balance) values (224, 'DEBIT', 15218.00);
insert into account (client_id, account_type, balance) values (52, 'CREDIT', 18366.00);
insert into account (client_id, account_type, balance) values (190, 'CREDIT', 18973.00);
insert into account (client_id, account_type, balance) values (194, 'CREDIT', 14495.00);
insert into account (client_id, account_type, balance) values (110, 'DEBIT', 3356.00);
insert into account (client_id, account_type, balance) values (93, 'CREDIT', 14773.00);
insert into account (client_id, account_type, balance) values (27, 'DEBIT', 18911.00);
insert into account (client_id, account_type, balance) values (114, 'CREDIT', 22171.00);
insert into account (client_id, account_type, balance, account_status) values (30, 'CREDIT', 15370.00, 'CLOSED');




insert into transaction (account_id, amount, transaction_time) values (1, -2443.00, NOW() - interval '14 days');
insert into transaction (account_id, amount, transaction_time) values (1, 1111.00, NOW() - interval '21 days');
insert into transaction (account_id, amount, transaction_time) values (1, 15337.00, NOW() - interval '27 days');
insert into transaction (account_id, amount, transaction_time) values (1, 3181.00, NOW() - interval '13 days');
insert into transaction (account_id, amount, transaction_time) values (2, -3870.00, NOW() - interval '13 days');
insert into transaction (account_id, amount, transaction_time) values (2, 2052.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (2, 1915.00, NOW() - interval '20 days');
insert into transaction (account_id, amount, transaction_time) values (2, 5160.00, NOW() - interval '6 days');
insert into transaction (account_id, amount, transaction_time) values (3, 15985.00, NOW() - interval '15 days');
insert into transaction (account_id, amount, transaction_time) values (3, 6257.00, NOW() - interval '13 days');
insert into transaction (account_id, amount, transaction_time) values (3, 7590.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (3, 16602.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (4, 14744.00, NOW() - interval '18 days');
insert into transaction (account_id, amount, transaction_time) values (4, 14048.00, NOW() - interval '6 days');
insert into transaction (account_id, amount, transaction_time) values (4, 159.00, NOW() - interval '20 days');
insert into transaction (account_id, amount, transaction_time) values (4, 4462.00, NOW() - interval '15 days');
insert into transaction (account_id, amount, transaction_time) values (5, -2873.00, NOW() - interval '19 days');
insert into transaction (account_id, amount, transaction_time) values (5, 4757.00, NOW() - interval '22 days');
insert into transaction (account_id, amount, transaction_time) values (5, 14206.00, NOW() - interval '8 days');
insert into transaction (account_id, amount, transaction_time) values (5, 16525.00, NOW() - interval '22 days');
insert into transaction (account_id, amount, transaction_time) values (6, 12050.00, NOW() - interval '20 days');
insert into transaction (account_id, amount, transaction_time) values (6, -2484.00, NOW() - interval '14 days');
insert into transaction (account_id, amount, transaction_time) values (6, -2640.00, NOW() - interval '24 days');
insert into transaction (account_id, amount, transaction_time) values (6, -1426.00, NOW() - interval '9 days');
insert into transaction (account_id, amount, transaction_time) values (7, 3891.00, NOW() - interval '24 days');
insert into transaction (account_id, amount, transaction_time) values (7, 6539.00, NOW() - interval '24 days');
insert into transaction (account_id, amount, transaction_time) values (7, -2899.00, NOW() - interval '29 days');
insert into transaction (account_id, amount, transaction_time) values (7, 3184.00, NOW() - interval '14 days');
insert into transaction (account_id, amount, transaction_time) values (8, 10088.00, NOW() - interval '23 days');
insert into transaction (account_id, amount, transaction_time) values (8, 2319.00, NOW() - interval '13 days');
insert into transaction (account_id, amount, transaction_time) values (8, 14224.00, NOW() - interval '28 days');
insert into transaction (account_id, amount, transaction_time) values (8, 4358.00, NOW() - interval '21 days');
insert into transaction (account_id, amount, transaction_time) values (9, 11223.00, NOW() - interval '3 days');
insert into transaction (account_id, amount, transaction_time) values (9, 9641.00, NOW() - interval '8 days');
insert into transaction (account_id, amount, transaction_time) values (9, 8231.00, NOW() - interval '27 days');
insert into transaction (account_id, amount, transaction_time) values (9, 1571.00, NOW() - interval '14 days');
insert into transaction (account_id, amount, transaction_time) values (10, 1257.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (10, -4258.00, NOW() - interval '2 days');
insert into transaction (account_id, amount, transaction_time) values (10, 11481.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (10, 3823.00, NOW() - interval '15 days');
insert into transaction (account_id, amount, transaction_time) values (11, 4760.00, NOW() - interval '28 days');
insert into transaction (account_id, amount, transaction_time) values (11, 5735.00, NOW() - interval '4 days');
insert into transaction (account_id, amount, transaction_time) values (11, 10071.00, NOW() - interval '20 days');
insert into transaction (account_id, amount, transaction_time) values (11, 8496.00, NOW() - interval '6 days');
insert into transaction (account_id, amount, transaction_time) values (12, 4597.00, NOW() - interval '5 days');
insert into transaction (account_id, amount, transaction_time) values (12, 11697.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (12, 7218.00, NOW() - interval '20 days');
insert into transaction (account_id, amount, transaction_time) values (12, 8628.00, NOW() - interval '8 days');
insert into transaction (account_id, amount, transaction_time) values (13, 19482.00, NOW() - interval '25 days');
insert into transaction (account_id, amount, transaction_time) values (13, -909.00, NOW() - interval '6 days');
insert into transaction (account_id, amount, transaction_time) values (13, 17690.00, NOW() - interval '29 days');
insert into transaction (account_id, amount, transaction_time) values (13, 524.00, NOW() - interval '16 days');
insert into transaction (account_id, amount, transaction_time) values (14, -1781.00, NOW() - interval '17 days');
insert into transaction (account_id, amount, transaction_time) values (14, 5601.00, NOW() - interval '3 days');
insert into transaction (account_id, amount, transaction_time) values (14, 5649.00, NOW() - interval '24 days');
insert into transaction (account_id, amount, transaction_time) values (14, 15138.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (15, 1998.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (15, 8889.00, NOW() - interval '21 days');
insert into transaction (account_id, amount, transaction_time) values (15, -850.00, NOW() - interval '17 days');
insert into transaction (account_id, amount, transaction_time) values (15, 14490.00, NOW() - interval '7 days');
insert into transaction (account_id, amount, transaction_time) values (16, -3721.00, NOW() - interval '18 days');
insert into transaction (account_id, amount, transaction_time) values (16, 2204.00, NOW() - interval '23 days');
insert into transaction (account_id, amount, transaction_time) values (16, 10547.00, NOW() - interval '18 days');
insert into transaction (account_id, amount, transaction_time) values (16, 17082.00, NOW() - interval '9 days');
insert into transaction (account_id, amount, transaction_time) values (17, 16187.00, NOW() - interval '12 days');
insert into transaction (account_id, amount, transaction_time) values (17, 8635.00, NOW() - interval '27 days');
insert into transaction (account_id, amount, transaction_time) values (17, 12397.00, NOW() - interval '15 days');
insert into transaction (account_id, amount, transaction_time) values (17, -3305.00, NOW() - interval '10 days');
insert into transaction (account_id, amount, transaction_time) values (18, 10196.00, NOW() - interval '8 days');
insert into transaction (account_id, amount, transaction_time) values (18, 10026.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (18, -3182.00, NOW() - interval '25 days');
insert into transaction (account_id, amount, transaction_time) values (18, 2696.00, NOW() - interval '15 days');
insert into transaction (account_id, amount, transaction_time) values (19, -328.00, NOW() - interval '2 days');
insert into transaction (account_id, amount, transaction_time) values (19, 11121.00, NOW() - interval '16 days');
insert into transaction (account_id, amount, transaction_time) values (19, 2813.00, NOW() - interval '28 days');
insert into transaction (account_id, amount, transaction_time) values (19, 15967.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (20, 8167.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (20, 7716.00, NOW() - interval '19 days');
insert into transaction (account_id, amount, transaction_time) values (20, 15012.00, NOW() - interval '29 days');
insert into transaction (account_id, amount, transaction_time) values (20, 10908.00, NOW() - interval '16 days');
insert into transaction (account_id, amount, transaction_time) values (21, 17733.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (21, 8507.00, NOW() - interval '4 days');
insert into transaction (account_id, amount, transaction_time) values (21, 9651.00, NOW() - interval '23 days');
insert into transaction (account_id, amount, transaction_time) values (21, 7125.00, NOW() - interval '23 days');
insert into transaction (account_id, amount, transaction_time) values (22, 11948.00, NOW() - interval '11 days');
insert into transaction (account_id, amount, transaction_time) values (22, 5898.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (22, 12259.00, NOW() - interval '1 days');
insert into transaction (account_id, amount, transaction_time) values (22, 19146.00, NOW());
insert into transaction (account_id, amount, transaction_time) values (23, -4296.00, NOW());
insert into transaction (account_id, amount, transaction_time) values (23, 15877.00, NOW());
insert into transaction (account_id, amount, transaction_time) values (23, 14001.00, NOW());
insert into transaction (account_id, amount, transaction_time) values (23, -3411.00, NOW());